### ISSUE TITLE
Is it possible to use arguments for the latexmk command?

### ISSUE THREAD

**Issue by LaserKaspar** [jonhue/pubtex#1]
My action fails because is an undefined control sequence. Everything compiles fine locally.

```No file _DABA.bbl.
./LaTeX/DA_Snowboards/_DABA.TEX:38: Undefined control sequence.
l.38 \studiengang
                 {Mediendesign - Gamedesign}
./LaTeX/DA_Snowboards/_DABA.TEX:38:  ==> Fatal error occurred, no output PDF fi
le produced!
Transcript written on _DABA.log.
Latexmk: Missing bbl file '_DABA.bbl' in following:
 No file _DABA.bbl.
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
  ```
  
  Is it possible to force the build?

**Comment by jonhue** [comment]
Make sure that there are no warnings locally, all files are committed, and that the paths are correct.
If it still doesn't compile, ask https://github.com/xu-cheng/latex-action. The pubtex action calls this action for the latex compile.
